import './globals.css';
import { Inter } from 'next/font/google';
import { ChakraProviders } from '@/utils/ChakraProviders';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Xtrata',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ChakraProviders>{children}</ChakraProviders>
      </body>
    </html>
  );
}
