import './globals.css';
import { Inter } from 'next/font/google';
import { ChakraProviders } from '@/utils/ChakraProviders';
import { poppins } from '@/utils/fonts';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Xtrata',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={poppins.className || inter.className}>
        <div className='bg-[url("/assets/img/bg.jpg")] bg-cover bg-center'>
          <ChakraProviders>{children}</ChakraProviders>
        </div>
      </body>
    </html>
  );
}
